spring.application.name=spring_boot

# Đổi đường dẫn Swagger UI (Mặc định: /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Đổi đường dẫn API Docs JSON (Mặc định: /v3/api-docs)
springdoc.api-docs.path=/api-docs

# Tự động sắp xếp các Endpoint và Tags theo thứ tự Alphabet
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Bật/tắt Swagger theo môi trường (ví dụ: tắt trên Production)
# springdoc.swagger-ui.enabled=false